//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace casestudy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentLogin
    {
        public int UserID { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Username { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public Nullable<int> ClassID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> FeeID { get; set; }
        public Nullable<int> AdmissionID { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Student Student { get; set; }
        public virtual Fee Fee { get; set; }
        public virtual Admission Admission { get; set; }
    }
}
